apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-report-cert
spec:
  secretName: test-report-cert-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "test-report.k8swrkshp.devopsplatforms.tv"
  issuerRef:
    name: cluster-issuer-devopsplatforms-tv
    kind: ClusterIssuer