apiVersion: batch/v1
kind: Job
metadata:
  name: robot-run
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: robot-test
        app.kubernetes.io/name: robot-test
    spec:
      restartPolicy: Never
      serviceAccountName: tester
      containers:
      - name: reports-webserver
        image: nginx:latest
        ports: 
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: reports
      - name: robot-run
        image: registry.humanitec.io/k8swrkshp/nils-test:0.0.3
        volumeMounts:
        - mountPath: /opt/robotframework/reports
          name: reports
      imagePullSecrets:
      - name: regcred
      volumes:
      - emptyDir: {}
        name: reports
