apiVersion: v1
kind: ServiceAccount
metadata:
  name: tester
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: tester-sa-token
  annotations:
    kubernetes.io/service-account.name: tester
