apiVersion: v1
data:
  index-html-file-content: |
    <H1>WELCOME TO THE NGINX PARTY!</H1>
    <img src="https://media.giphy.com/media/EktbegF3J8QIo/giphy.gif" alt="party!">
kind: ConfigMap
metadata:
  name: nginx-index-configmap
